# Generated by Django 5.2.8 on 2025-11-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Modern POS Business', max_length=200)),
                ('business_address', models.TextField(blank=True)),
                ('business_phone', models.CharField(blank=True, max_length=20)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('currency', models.CharField(choices=[('NGN', 'Naira (₦)'), ('USD', 'Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'Pound (£)')], default='NGN', max_length=3)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('show_inventory', models.BooleanField(default=True)),
                ('show_receipts', models.BooleanField(default=True)),
                ('show_analytics', models.BooleanField(default=True)),
                ('show_reports', models.BooleanField(default=True)),
                ('enable_sms', models.BooleanField(default=False)),
                ('enable_email', models.BooleanField(default=False)),
                ('primary_color', models.CharField(default='#667eea', help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(default='#764ba2', help_text='Hex color code', max_length=7)),
                ('accent_color', models.CharField(default='#f093fb', help_text='Hex color code', max_length=7)),
                ('card_radius', models.IntegerField(default=20, help_text='Border radius in pixels')),
                ('card_shadow', models.CharField(default='0 10px 30px rgba(0, 0, 0, 0.1)', help_text='CSS shadow value', max_length=50)),
                ('receipt_header', models.TextField(blank=True, help_text='Text to appear at top of receipts')),
                ('receipt_footer', models.TextField(blank=True, help_text='Text to appear at bottom of receipts')),
                ('show_receipt_logo', models.BooleanField(default=True)),
                ('analytics_refresh_rate', models.IntegerField(default=30, help_text='Refresh rate in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
