# Generated by Django 4.2.26 on 2025-12-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_dailysalessummary_unusualtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorder',
            name='payment_method',
            field=models.CharField(choices=[('pos', 'POS/ATM Card'), ('transfer', 'Bank Transfer'), ('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('credit', 'Credit')], max_length=20),
        ),
    ]
