# Generated by Django 4.2.26 on 2025-12-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_posorder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('pos', 'POS/ATM Card'), ('transfer', 'Bank Transfer'), ('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('credit', 'Credit'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], max_length=20),
        ),
    ]
