# Generated by Django 5.2.8 on 2025-12-05 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_paymenttransaction_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('products', 'Products'), ('customers', 'Customers'), ('orders', 'Orders')], max_length=20)),
                ('file_name', models.CharField(max_length=200)),
                ('total_records', models.PositiveIntegerField()),
                ('successful_records', models.PositiveIntegerField(default=0)),
                ('failed_records', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('error_log', models.TextField(blank=True, help_text='JSON formatted error log')),
                ('imported_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bulk Import Log',
                'verbose_name_plural': 'Bulk Import Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyLimitSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_order_limit', models.PositiveIntegerField(default=50, help_text='Maximum orders per day')),
                ('daily_sales_limit', models.DecimalField(decimal_places=2, default=50000, help_text='Maximum sales amount per day', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Limit Setting',
                'verbose_name_plural': 'Daily Limit Settings',
            },
        ),
        migrations.CreateModel(
            name='DailyOrderCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Order Count',
                'verbose_name_plural': 'Daily Order Counts',
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cashier', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.posorder')),
            ],
            options={
                'verbose_name': 'Transaction History',
                'verbose_name_plural': 'Transaction Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['date'], name='sales_trans_date_ed4d18_idx'), models.Index(fields=['cashier'], name='sales_trans_cashier_8a4969_idx'), models.Index(fields=['payment_method'], name='sales_trans_payment_921ff8_idx')],
            },
        ),
    ]
